### ISSUE TITLE
Carrier video calling

### ISSUE THREAD

**Issue by Debrup1998** [KhushrajRathod/VoLTE-Fix#10]
Sir in redmi 7a(pine) volte works fine but carrier video calling doesn't work at all. Can you please imclude that?

**Comment by KhushrajRathod** [comment]
The 32bit IMS apk is already built from a Redmi 7A, so I don't know if this can be fixed

**Comment by Debrup1998** [comment]
There is a magisk gsi built for redmi 7a that turns on wifi calling option but shows unable to connect if the video call is made
