### ISSUE TITLE
64-bit IMS apk possibly broken

### ISSUE THREAD

**Issue by ron9k** [KhushrajRathod/VoLTE-Fix#3]
Hello! I flashed the new flashable zip in twrp. I got error: invalid zip file format. error installing zip file.
I didnt check MD5 checksum...

**Comment by KhushrajRathod** [comment]
Seems weird. Try downloading the zip again (v2.1.0), and flash. I can assure you that the zip is in correct format as I’ve tested it myself

**Comment by ron9k** [comment]
Yes did it now. No error in twrp. But no volte. Ims not recognised. What am
I doing wrong?
😊

fre. 5. jun. 2020, 11:01 skrev Khushraj Rathod <notifications@github.com>:

> Seems weird. Try downloading the zip again (v2.1.0), and flash. I can
> assure you that the zip is in correct format as I’ve tested it myself
>

**Comment by KhushrajRathod** [comment]
Are you using a Qualcomm, non-samsung device?

**Comment by ron9k** [comment]
Yes oneplus 6

fre. 5. jun. 2020, 13:28 skrev Khushraj Rathod <notifications@github.com>:

> Are you using a Qualcomm, non-samsung device?
>

**Comment by KhushrajRathod** [comment]
And which operating system are you using?

**Comment by ron9k** [comment]
Phh aosp 10 (quack) v219

fre. 5. jun. 2020, 13:34 skrev Khushraj Rathod <notifications@github.com>:

> And which operating system are you using?
>

**Comment by KhushrajRathod** [comment]
Alright could you tell me the contents of /system/priv-app/ims/folder ?

Sent from Outlook Mobile<https://aka.ms/blhgte>

**Comment by ron9k** [comment]
I'm at work. I will do when I get home. Thank you for your help 😊

fre. 5. jun. 2020, 14:14 skrev Khushraj Rathod <notifications@github.com>:

**Comment by ron9k** [comment]
Hi. I have no ims folder under /system/priv-app/. 
In twrp I get: 
Mounting system..
Moving files...
Detected 64bit architecture
Extracting persistprop binary...
Setting props..
Done!
*#*#4636#*#* shows no ims registered

**Comment by ron9k** [comment]
I found ims folder under root. system/priv-app/ims it contain ims.apk and lib folder. 
In lib folder, arm and arm64 folder. In arm64 libimscamera_jni.so and libimsmedia_jni.so

**Comment by KhushrajRathod** [comment]
Alright so seems like there’s nothing wrong with the package installer, and VoLTE should be working, unless there's something wrong with the last ims apk I've pushed.

Reboot to TWRP and replace the ims apk that's inside /system/priv-app/ims/ with [this one](https://github.com/KhushrajRathod/VoLTE-Fix/raw/0c73b822fd18b9b3627c2c20b8eb14222fcb2f95/binder64/ims/ims.apk), reboot twice after that, and check

**Comment by KhushrajRathod** [comment]
If you don't know how to replace files in TWRP, reply and I'll make you another flashable zip so you can test it

**Comment by ron9k** [comment]
I replaced APK file with FX filemanager. Rebooted twice, but sadly not working 🥺
I found nothing new in build.prop...

**Comment by KhushrajRathod** [comment]
If you use magisk, replacing APK with FX filemanager will not work. You will have to use TWRP. There shouldn't be anything new in build.prop anyway. 

Run the following commands in a terminal as root (preferably TWRP terminal) one by one.

    getprop persist.dbg.allow_ims_off
    getprop persist.dbg.volte_avail_ovr
    getprop persist.dbg.vt_avail_ovr
    getprop persist.dbg.wfc_avail_ovr
    getprop persist.sys.phh.ims.caf

and give output

**Comment by ron9k** [comment]
![Screenshot_20200605-204350](https://user-images.githubusercontent.com/66268091/83911875-53f41380-a76d-11ea-97cf-18cdb8f7b2d8.png)

**Comment by KhushrajRathod** [comment]
Are you using Magisk??

**Comment by KhushrajRathod** [comment]
Anyway...
Run as root

```
setprop persist.dbg.allow_ims_off 1
setprop persist.dbg.volte_avail_ovr 1
setprop persist.dbg.vt_avail_ovr 1
setprop persist.dbg.wfc_avail_ovr 1
setprop persist.sys.phh.ims.caf true
```

**Comment by ron9k** [comment]
yes have magisk

**Comment by ron9k** [comment]
![Screenshot_20200605-205519](https://user-images.githubusercontent.com/66268091/83912896-ea750480-a76e-11ea-9944-8eea96773322.png)

**Comment by KhushrajRathod** [comment]
And reboot twice again

**Comment by ron9k** [comment]
![Screenshot_20200605-205946](https://user-images.githubusercontent.com/66268091/83913265-8bfc5600-a76f-11ea-821f-266c4f2982bd.png)

**Comment by KhushrajRathod** [comment]
I can't understand this, did you get VoLTE working?

**Comment by KhushrajRathod** [comment]
Well great!
