### ISSUE TITLE
Incorrect lib folder location

### ISSUE THREAD

**Issue by nopeno** [KhushrajRathod/VoLTE-Fix#4]
i got some error like this:   (does adding a permission.xml resolve it?)

06-08 15:17:05.329  4218  4218 E System  : ************ Failure starting system services
06-08 15:17:05.329  4218  4218 E System  : java.lang.IllegalStateException: Signature|privileged permissions not in privapp-permissions whitelist: {org.codeaurora.ims: android.permission.READ_PRECISE_PHONE_STATE, org.codeaurora.ims: android.permission.INTERACT_ACROSS_USERS, org.codeaurora.ims: android.permission.SUBSTITUTE_NOTIFICATION_APP_NAME}
06-08 15:17:05.329  4218  4218 E System  : 	at com.android.server.pm.permission.PermissionManagerService.systemReady(PermissionManagerService.java:2970)
06-08 15:17:05.329  4218  4218 E System  : 	at com.android.server.pm.permission.PermissionManagerService.access$100(PermissionManagerService.java:122)
06-08 15:17:05.329  4218  4218 E System  : 	at com.android.server.pm.permission.PermissionManagerService$PermissionManagerServiceInternalImpl.systemReady(PermissionManagerService.java:3031)
06-08 15:17:05.329  4218  4218 E System  : 	at com.android.server.pm.PackageManagerService.systemReady(PackageManagerService.java:21791)
06-08 15:17:05.329  4218  4218 E System  : 	at com.android.server.SystemServer.startOtherServices(SystemServer.java:1993)
06-08 15:17:05.329  4218  4218 E System  : 	at com.android.server.SystemServer.run(SystemServer.java:513)
06-08 15:17:05.329  4218  4218 E System  : 	at com.android.server.SystemServer.main(SystemServer.java:350)
06-08 15:17:05.329  4218  4218 E System  : 	at java.lang.reflect.Method.invoke(Native Method)
06-08 15:17:05.329  4218  4218 E System  : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
06-08 15:17:05.329  4218  4218 E System  : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:908)
06-08 15:17:05.329  4218  4430 D HalDevMgr: canIfaceComboSupportRequest: chipInfo={chipId=0, availableModes=[{.id = 3, .availableCombinations = [{.limits = [{.types = [0], .maxIfaces = 1}, {.types = [1], .maxIfaces = 1}]}, {.limits = [{.types = [0], .maxIfaces = 1}, {.types = [2, 3], .maxIfaces = 1}]}]}], currentModeIdValid=false, currentModeId=0, ifaces[1].length=0, ifaces[0].length=0, ifaces[2].length=0, ifaces[3].length=0), chipMode={.id = 3, .availableCombinations = [{.limits = [{.types = [0], .maxIfaces = 1}, {.types = [1], .maxIfaces = 1}]}, {.limits = [{.types = [0], .maxIfaces = 1}, {.types = [2, 3], .maxIfaces = 1}]}]}, chipIfaceCombo=[I@d65ea90, ifaceType=0, lowPriority=true
06-08 15:17:05.329  4218  4218 D SystemServerTiming: MakePackageManagerServiceReady took to complete: 23ms
06-08 15:17:05.329  4218  4218 E Zygote  : System zygote died with exception
06-08 15:17:05.329  4218  4218 E Zygote  : java.lang.IllegalStateException: Signature|privileged permissions not in privapp-permissions whitelist: {org.codeaurora.ims: android.permission.READ_PRECISE_PHONE_STATE, org.codeaurora.ims: android.permission.INTERACT_ACROSS_USERS, org.codeaurora.ims: android.permission.SUBSTITUTE_NOTIFICATION_APP_NAME}
06-08 15:17:05.329  4218  4218 E Zygote  : 	at com.android.server.pm.permission.PermissionManagerService.systemReady(PermissionManagerService.java:2970)
06-08 15:17:05.329  4218  4218 E Zygote  : 	at com.android.server.pm.permission.PermissionManagerService.access$100(PermissionManagerService.java:122)
06-08 15:17:05.329  4218  4218 E Zygote  : 	at com.android.server.pm.permission.PermissionManagerService$PermissionManagerServiceInternalImpl.systemReady(PermissionManagerService.java:3031)
06-08 15:17:05.329  4218  4218 E Zygote  : 	at com.android.server.pm.PackageManagerService.systemReady(PackageManagerService.java:21791)
06-08 15:17:05.329  4218  4218 E Zygote  : 	at com.android.server.SystemServer.startOtherServices(SystemServer.java:1993)
06-08 15:17:05.329  4218  4218 E Zygote  : 	at com.android.server.SystemServer.run(SystemServer.java:513)
06-08 15:17:05.329  4218  4218 E Zygote  : 	at com.android.server.SystemServer.main(SystemServer.java:350)
06-08 15:17:05.329  4218  4218 E Zygote  : 	at java.lang.reflect.Method.invoke(Native Method)
06-08 15:17:05.329  4218  4218 E Zygote  : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
06-08 15:17:05.329  4218  4218 E Zygote  : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:908)
06-08 15:17:05.329  4218  4218 D AndroidRuntime: Shutting down VM
06-08 15:17:05.330  4218  4218 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
06-08 15:17:05.330  4218  4218 E AndroidRuntime: java.lang.IllegalStateException: Signature|privileged permissions not in privapp-permissions whitelist: {org.codeaurora.ims: android.permission.READ_PRECISE_PHONE_STATE, org.codeaurora.ims: android.permission.INTERACT_ACROSS_USERS, org.codeaurora.ims: android.permission.SUBSTITUTE_NOTIFICATION_APP_NAME}
06-08 15:17:05.330  4218  4218 E AndroidRuntime: 	at com.android.server.pm.permission.PermissionManagerService.systemReady(PermissionManagerService.java:2970)
06-08 15:17:05.330  4218  4218 E AndroidRuntime: 	at com.android.server.pm.permission.PermissionManagerService.access$100(PermissionManagerService.java:122)
06-08 15:17:05.330  4218  4218 E AndroidRuntime: 	at com.android.server.pm.permission.PermissionManagerService$PermissionManagerServiceInternalImpl.systemReady(PermissionManagerService.java:3031)
06-08 15:17:05.330  4218  4218 E AndroidRuntime: 	at com.android.server.pm.PackageManagerService.systemReady(PackageManagerService.java:21791)
06-08 15:17:05.330  4218  4218 E AndroidRuntime: 	at com.android.server.SystemServer.startOtherServices(SystemServer.java:1993)
06-08 15:17:05.330  4218  4218 E AndroidRuntime: 	at com.android.server.SystemServer.run(SystemServer.java:513)
06-08 15:17:05.330  4218  4218 E AndroidRuntime: 	at com.android.server.SystemServer.main(SystemServer.java:350)
06-08 15:17:05.330  4218  4218 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-08 15:17:05.330  4218  4218 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
06-08 15:17:05.330  4218  4218 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:908)

**Comment by KhushrajRathod** [comment]
I just added an Issue template - Please complete the information

Describe the bug A clear and concise description of what the bug is.

Method of Installation Which method of installation did you use? (Eg. Install Script when booted, Install Script when in recovery, Flashable Zip)

Smartphone (please complete the following information):

    Device: [e.g. OnePlus 6]
    OS: [e.g. Android 10]
    GSI Base version: [eg. AOSP v217]
    VoLTE-Fix Version: [e.g. 2.2.0]

Magisk Are you using magisk?

Additional context Add any other context about the problem here.

**Comment by nopeno** [comment]
**Describe**
after i flashed volte-fix (from master branch) and reboot, the system showes "ANDROID" logo and hang.
and i got the log by `adb logcat` command

** Method of Installation **
```
git pull
install.sh 64
```

**Smartphone**
```
device: mi8ee
OS: android 10
GSI Base version: AOSP v219 (phh, with gapps)
VoLTE-fix Version: 2.2.0
```
**Magisk**
no

**Comment by KhushrajRathod** [comment]
Ok, so everything seems okay with your device, I don't know why it should bootloop... I don't think pushing the xml to system/etc/permissions will make a difference either as it's already bundled in your OS version, but you could give it a go (If the same xml is not already present in /system/etc/permissions, because then it's pointless)

Also, try using Version 2.1.0 (First run uninstaller) because it uses a different IMS apk

Join this group and ask phhusson for further help: https://t.me/phhtreble

**Comment by nopeno** [comment]
version 2.1.0 doesnot work. maybe i need to dump the newest ims.apk from official rom

**Comment by KhushrajRathod** [comment]
Alright, if you can get a log, you should ask here: https://telegram.me/phhtreble

**Comment by KhushrajRathod** [comment]
Hi, you might want to try v3, and push qti.xml to /system/etc/permissions

**Comment by nopeno** [comment]
bootloop is gone. unfortunately, the mobile network is lost, but the wifi is work. it resumed after uninstalled.

**Comment by nopeno** [comment]
also, dial *#*#4636#*#*  failed either.

**Comment by nopeno** [comment]
> Hi, you might want to try v4

bootloop is gone. unfortunately, the mobile network is lost, but the wifi is work. it resumed after uninstalled.
and, dial ##4636## failed either.

**Comment by KhushrajRathod** [comment]
Ok, try building your own ims.apk using the build64.sh script: https://github.com/phhusson/apps_repacker_aosp/tree/q/VoLTE-CAF

You'll need to download your system dump from https://git.rip

**Comment by nopeno** [comment]
> Ok, try building your own ims.apk using the build64.sh script: https://github.com/phhusson/apps_repacker_aosp/tree/q/VoLTE-CAF
> 
> You'll need to download your system dump from https://git.rip/dumps

well, it is ok with repacked ims.apk. and, libimsmedia_jni.so and libimscamera_jni.so need to be pushed into /system/lib64/

**Comment by KhushrajRathod** [comment]
Well yes, I've heard someone say that before, thanks for reporting it

**Comment by KhushrajRathod** [comment]
I think it was my fault that the lib had to pushed to /system/lib64, that shouldn't be required...
Could you try the [continuous zip](https://github.com/KhushrajRathod/VoLTE-Fix/releases/download/continuous/GSI-Qualcomm-VoLTE-Fix.zip)?
Thanks

**Comment by nopeno** [comment]
I will try later
