### ISSUE TITLE
VoLTE not activating in Redmi 6 Pro

### ISSUE THREAD

**Issue by namandixit** [KhushrajRathod/VoLTE-Fix#5]
- [x] I'm using a device with a Qualcomm processor
- [x] I'm using a non-samsung device

**Describe the bug**
Calls can not be made using VoLTE only SIMs (Reliance Jio in India). There is no VoLTE label either. Installing a second time results in the device completely stopping to detect any SIM card.

**Method of Installation**
Flashable Zip (through TWRP), and `install.sh` script (run on Linux after booting phone in TWRP and mounting System)

**Smartphone (please complete the following information):**
 - Device: Redmi 6 Pro (sakura india)
 - OS: Android 10
 - GSI Base version: AOSP 10.0 v220
 - VoLTE-Fix Version: 2.2.0

**Magisk**
No, the phone is not using magisk - Unsecurized

**Additional context**
Trying the `getprop` in TWRP terminal results in empty lines for the relevant properties listed in README, even after flashing the zip. Also, I am using in-memory TWRP (through `fastboot boot twrp.img`) instead of installing it in system.

**Comment by KhushrajRathod** [comment]
Try

**Comment by KhushrajRathod** [comment]
Try
```
setprop persist.dbg.allow_ims_off 1
setprop persist.dbg.volte_avail_ovr 1
setprop persist.dbg.vt_avail_ovr 1
setprop persist.dbg.wfc_avail_ovr 1
setprop persist.sys.phh.ims.caf true
```
while booted into system

**Comment by namandixit** [comment]
Doing this and rebooting resulted again in both sim cards simply not getting detected at all.

**Comment by namandixit** [comment]
Rebooting multiple times after flashing the zip has no effect, neither does VoLTE works, nor does the sim cards get disabled, and `*#*#4636#*#*` has all VoLTE related options greyed out.

After running the above commands, `*#*#4636#*#*` has all VoLTE related options enabled, but VoLTE label is still not displayed.

After rebooting, `*#*#4636#*#*` stops working (clicking on "Phone Information" opens the screen momentarily, and then puts me back on the default `*#*#4636#*#*` option screen). `Settings`->`Network and Internet`->`Mobile Network` is greyed out. And the indicator for mobile signals has disappeared.

**Comment by KhushrajRathod** [comment]
Okay, you should try the release v2.1.0 (flashable zip - First run the uninstaller). Your phone is 64bit and v2.1.0 uses the IMS apk I built, which might solve your problem

**Comment by namandixit** [comment]
One thing I should mention (not sure if relevant) is that I am unable to decrypt using TWRP, and thus am forced to simply click Cancel.

**Comment by KhushrajRathod** [comment]
Yes so that's why I think you cannot set the properties using TWRP. Nevermind, run the uninstaller zip, install v2.1.0, and check while booted into system if the props are set using getprop (after running su)

**Comment by namandixit** [comment]
@KhushrajRathod  After flashing v2.1.0, on the first reboot, VoLTE still didn't work (couldn't place class from Jio, and no label). After second reboot (without doing anything else), the sim cards are disabled once again.

**Comment by KhushrajRathod** [comment]
Okay, I don't know then, you may get help here: https://telegram.me/phhtreble - Be sure to include a log

**Comment by namandixit** [comment]
Sure, no problem. How can I obtain a log, if you don't mind?

**Comment by KhushrajRathod** [comment]
From a computer connected to your phone, run

`adb logcat`

**Comment by KhushrajRathod** [comment]
Hi, you might want to try v3

**Comment by namandixit** [comment]
Sorry, I no longer have that phone. Feel free to close the issue.
